language: common-lisp
sudo: false

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

os:
  - osx
  - linux

addons:
  apt:
    packages:
      - libc6-i386
      - openjdk-7-jre

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_BRANCH=master
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
  matrix:
    - LISP=sbcl-bin
    - LISP=ccl-bin
    - LISP=abcl
    - LISP=clisp
    - LISP=ecl
    - LISP=cmucl
    - LISP=alisp

matrix:
  allow_failures:
    - env: LISP=clisp
    - env: LISP=abcl
    - env: LISP=ecl
    - env: LISP=cmucl
    - env: LISP=alisp

before_script:
  - ros --version
  - ros config

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh
  - ros install prove

script:
  - run-prove ql-checkout-test.asd
